### ISSUE TITLE
basename is not equivalent to the utility

### ISSUE THREAD

**Issue by calimeroteknik** [dylanaraps/pure-bash-bible#83]
This shouldn't be as hard as dirname; trailing slashes are the crux in the first counter-examples, then there is lack of support for the second optional argument, which nobody knows about anyway:
```sh
~ $ basename_pbb() {
    # Usage: basename "path"
    : "${1%/}"
    printf '%s\n' "${_##*/}"
}
~ $ basename_pbb something//

~ $ basename something//
something
~ $ basename_pbb /

~ $ basename /
/
~ $ basename_pbb dir/something thing
something
~$ basename dir/something thing
some
```
The POSIX standard helps, https://pubs.opengroup.org/onlinepubs/9699919799/

According to this, some compliant implementation could go like this:
* If string consists entirely of `/` characters, the result is a single `/` character.
* Otherwise:
  * If there are any trailing `/` characters in string, they shall be removed.
  * If there are any `/` characters remaining in string, the prefix of string up to and including the last `/` character in string shall be removed.
* If the suffix operand is present, is not identical to the characters remaining in string, and is identical to a suffix of the characters remaining in string, the suffix suffix shall be removed from string. Otherwise, string is not modified by this step. It shall not be considered an error if suffix is not found in string.

Meaning that this implementation is spec-conformant:
```sh
basename_pbb() {
    # Usage: basename "path" ["suffix"]
    local tmp
    if [[ $1 =~ ^/+$ ]]; then
        tmp=/
    else
        tmp=${1%"${1##*[!/]}"} # $1 without trailing slashes
        tmp=${tmp##*/} # $tmp without its longest prefix ending in a slash
    fi
    [[ $tmp != "$2" ]] && tmp=${tmp%"$2"}
    printf '%s\n' "$tmp"
}
```
If you want to have fun codegolfing it, be my guest! But don't remove the quotes around `$2`, because the asterisk and question mark characters are legal in filenames.

**Comment by dylanaraps** [comment]
Thanks for the detailed breakdown. :+1:

From what I understand with `tmp=${tmp%"$2"}`, the quotes should be omit-able. Expansions shouldn't be done on unquoted variables here no?

**Comment by calimeroteknik** [comment]
I added the warning precisely because they are!

**Comment by dylanaraps** [comment]
I couldn't reproduce the expansion in testing(?).

Anyway, here's my implementation:

```sh
basename_sh() {
    # Usage: basename "path"
    dir=${1%${1##*[!/]}}
    dir=${dir##*/}
    dir=${dir%"$2"}

    printf '%s\n' "${dir:-/}"
}
```

Tests passed:

```
basename /var/db/kiss/
basename /var/db/kiss
basename /var/db/kiss//////
basename /../dsad/asdasda/file.jpg
basename ~/Pictures/Wallpapers/img.jpg .jpg
basename ~/Pictures/Wallpapers/\*.jpg
basename ~/Pictures/Wallpapers/\?.jpg
basename /var
basename /var/
basename //
basename something//
basename .
basename ./
```

**Comment by calimeroteknik** [comment]
>I couldn't reproduce the expansion in testing(?).

Remove quotes around the second occurrence of `$2` and run with arguments `foobar 'f*r'` to see the horror.

**Comment by dylanaraps** [comment]
I stand corrected!

I didn't know about this and shellcheck doesn't warn about this either. Neat!

**Comment by dylanaraps** [comment]
I've pushed my implementation (with quotes!) to `master`. Apologies for not immediately believing you!

**Comment by calimeroteknik** [comment]
Well, shellcheck doesn't actually check shell, or at least… completely.  
It just looks for a series of known-to-be-suspicious things in the unsuspecting beginner's scripts, but will miss a ton of things, and certainly doesn't know what you meant to write, it just sees what you wrote.

No worries, I smiled at the question you asked in doubt (`man bash` contains the answer).

Clever codegolfing, although the part about the unquoted string of slashes in the substitution… yeah, that's not a glob character so that doesn't change behaviour, I know… yet it tickles a little bit. I included them for… properness. If such a thing exists in bash…

A bug remains: the comment does not mention the optional parameter `prefix`.

Going further, I think that the simple fact you couldn't reproduce the expansion problem speaks for itself that bash is way too tricky that nobody in their right mind should be writing programs in bash… myself included, really. :)

This is a reason I moved away from bash to automatically checking specification conformance using type systems. Why test at all, when you can prove?

**Comment by calimeroteknik** [comment]
Looking at your implementation, two problems remain:

1/ I don't think that `dir` is the right variable name here

2/ Actually you should not have removed the equality test before removing the suffix, because the spec says

>If the suffix operand is present, is not identical to the characters remaining in string

And sure enough, `basename_sh foo foo` returns `/` instead of `foo` because the empty string (which is an impossible filename) was reused to encode that case in order to drop the conditional in that codegolfing.

**Comment by dylanaraps** [comment]
Fixed.

```sh
basename() {
    # Usage: basename "path" ["suffix"]
    local tmp

    tmp=${1%${1##*[!/]}}
    tmp=${tmp##*/}
    tmp=${tmp%"${2/$1}"}

    printf '%s\n' "${tmp:-/}"
}
```

**Comment by calimeroteknik** [comment]
Unfortunately, still not there, you persist in not quoting variables that get expanded!

https://mywiki.wooledge.org/BashGuide/Practices
>And for heaven's sake, "Use more quotes!" Protect your strings and parameter expansions from WordSplitting. Word splitting will eat your babies if you don't quote things properly. 

`$tmp` is unquoted in `"${2/$tmp}"`. What could possibly go wrong?

Run with arguments `'**' '*'`.  
`**` is a valid filename, and `*` is indeed a suffix to remove from that. But the filename itself is expanded, and being a valid glob eats the suffix argument, nullifying the desired effect (suffix replacement).

I have not yet found a way to reveal a difference in semantics between `${1##*[!/]}` quoted or unquoted, but stay nervous! Not finding bugs is not proof of their absence. Quoting variables is however an easy way to prove that they won't undergo some bizarre expansion phenomenon that none of your tests will catch.

**Comment by dylanaraps** [comment]
Fixed (*quoted both mentioned cases*). Thanks for the insights.

**Comment by calimeroteknik** [comment]
I can now determine with reasonable⁽¹⁾ certainty that your implementation of `basename(1)` is POSIX-conformant. :)

⁽¹⁾ I did not use computer-assisted formal methods to determine this, so the risk is not zero; errare humanum est.
